// Generated by CoffeeScript 1.8.0
(function() {

  // これらはライフサイクル、イベントリスナ

  chrome.runtime.onMessage.addListener(function(message) {
	//window.alert('c');
    if (message.type === 'setBadgeText') {
      return chrome.browserAction.setBadgeText({
        text: message.value
      });
    }
  });

  chrome.tabs.onActivated.addListener(function(activeInfo) {
	window.alert('a');

	// タブを消す処理
	chrome.tabs.getSelected(null, function(tab){
		//chrome.tabs.remove(tab.id, function() {});
	});
    return chrome.tabs.sendMessage(activeInfo.tabId, {
      type: 'onActivated'
    });
  });

  chrome.tabs.onUpdated.addListener(function(tabId, changeInfo) {
	//window.alert('b');
    if (changeInfo.status === 'complete') {
      return chrome.tabs.sendMessage(tabId, {
        type: 'onActivated'
      });
    }
  });

}).call(this);
